allprojects {
    repositories {
        maven { url = uri("/root/local-maven-repo") }
        google()
        mavenCentral()
    }
}

rootProject.layout.buildDirectory.value(rootProject.layout.projectDirectory.dir("../build"))

subprojects {
    project.layout.buildDirectory.value(
        rootProject.layout.buildDirectory.dir(project.name)
    )
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}

subprojects {
    plugins.withId("com.android.application") {
        android {
            ndkVersion = "27.2.12479018"
        }
    }

    plugins.withId("com.android.library") {
        android {
            ndkVersion = "27.2.12479018"
        }
    }
}
